{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nbcss.logisticscontrol",
    "module": "createlogisticscontrol",
    "version": "0.1.0-neoforge-1.21.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "createlogisticscontrol-0.1.0-neoforge-1.21.1-SNAPSHOT.jar",
          "url": "createlogisticscontrol-0.1.0-neoforge-1.21.1-SNAPSHOT.jar",
          "size": 106139,
          "sha512": "f24170f2d7c64a9869a0b669bcf4e3f9ee4a28302bea4e1c442b5ca0fe82abb9b544cc5ddaa0b9b34b427e9b15ffd91884c26abd7119c1f4670f80e21c0caa70",
          "sha256": "35c16ac5a7931a944e754b8198f77bbc8c22b017a03e2b22bac5b63be705898c",
          "sha1": "291356c7d0c70f0ea20dbb95ff23a78a40cf7d5a",
          "md5": "ad420737a3f7cf34c6d8ccc85cc9ad84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createlogisticscontrol-0.1.0-neoforge-1.21.1-SNAPSHOT.jar",
          "url": "createlogisticscontrol-0.1.0-neoforge-1.21.1-SNAPSHOT.jar",
          "size": 106139,
          "sha512": "f24170f2d7c64a9869a0b669bcf4e3f9ee4a28302bea4e1c442b5ca0fe82abb9b544cc5ddaa0b9b34b427e9b15ffd91884c26abd7119c1f4670f80e21c0caa70",
          "sha256": "35c16ac5a7931a944e754b8198f77bbc8c22b017a03e2b22bac5b63be705898c",
          "sha1": "291356c7d0c70f0ea20dbb95ff23a78a40cf7d5a",
          "md5": "ad420737a3f7cf34c6d8ccc85cc9ad84"
        }
      ]
    }
  ]
}
