{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nbcss.createfactorycontroller",
    "module": "createfactorycontroller",
    "version": "1.2.2-neoforge-1.21.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "url": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "size": 2159735,
          "sha512": "7f81e1ba33a3e1b1aade90ce441819af71c14ff052754625162ab7a6e816d786ab838adfa77ba4d60169ce3daf30b7e6466fac0d924e24f3b9c0ead075e768ed",
          "sha256": "7b606e356a4c66eb65b7ad123c52bbb2ed2eefa22c58067791d6964a753287cb",
          "sha1": "adeb8c044600c11bb9dbb9618aa9e57cccfae877",
          "md5": "fdb456e2941a32295dc478f1d8137058"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "url": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "size": 2159735,
          "sha512": "7f81e1ba33a3e1b1aade90ce441819af71c14ff052754625162ab7a6e816d786ab838adfa77ba4d60169ce3daf30b7e6466fac0d924e24f3b9c0ead075e768ed",
          "sha256": "7b606e356a4c66eb65b7ad123c52bbb2ed2eefa22c58067791d6964a753287cb",
          "sha1": "adeb8c044600c11bb9dbb9618aa9e57cccfae877",
          "md5": "fdb456e2941a32295dc478f1d8137058"
        }
      ]
    }
  ]
}
