{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nbcss.createfactorycontroller",
    "module": "createfactorycontroller",
    "version": "1.2.2-neoforge-1.21.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "url": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "size": 1226217,
          "sha512": "9b49a003bdd5286f5c5e02dffeaac77796c0fdc751bb7546b5bbc5c3dfcc40cebf7fda04d6fd057aa93c1488fb8710612f2a9635f565834e512d3a0c3c82af59",
          "sha256": "deb44824c74b23e17f61d20c64a0e6513701a5c49b90b453869157b77414b416",
          "sha1": "2b895da70935d0b67fb182cbbd098326bb20fe4e",
          "md5": "2dc7e8d7984e26ab7d65e5a18e00381e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "url": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "size": 1226217,
          "sha512": "9b49a003bdd5286f5c5e02dffeaac77796c0fdc751bb7546b5bbc5c3dfcc40cebf7fda04d6fd057aa93c1488fb8710612f2a9635f565834e512d3a0c3c82af59",
          "sha256": "deb44824c74b23e17f61d20c64a0e6513701a5c49b90b453869157b77414b416",
          "sha1": "2b895da70935d0b67fb182cbbd098326bb20fe4e",
          "md5": "2dc7e8d7984e26ab7d65e5a18e00381e"
        }
      ]
    }
  ]
}
