{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nbcss.createfactorycontroller",
    "module": "createfactorycontroller",
    "version": "1.2.2-neoforge-1.21.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "url": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "size": 2172748,
          "sha512": "cbbeb6d45d19aafda2abc8279522c82e87dae222fc9e6bc173b5a5908ca37fbc3bf9d2bc5d764d324f785c3a3f7ea72743f84649bdc58371d14b08286a6a359a",
          "sha256": "79ac38866fafee41c73d68748a213733572128f0f2911b0ca25a451a8315ec5e",
          "sha1": "513e4ddf2a3a23d8c6ab657fa1ea12d8ffd19596",
          "md5": "67619abc95c796a2f4dd52ef6f0aff1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "url": "createfactorycontroller-1.2.2-neoforge-1.21.1-SNAPSHOT.jar",
          "size": 2172748,
          "sha512": "cbbeb6d45d19aafda2abc8279522c82e87dae222fc9e6bc173b5a5908ca37fbc3bf9d2bc5d764d324f785c3a3f7ea72743f84649bdc58371d14b08286a6a359a",
          "sha256": "79ac38866fafee41c73d68748a213733572128f0f2911b0ca25a451a8315ec5e",
          "sha1": "513e4ddf2a3a23d8c6ab657fa1ea12d8ffd19596",
          "md5": "67619abc95c796a2f4dd52ef6f0aff1d"
        }
      ]
    }
  ]
}
